{% set name = "mkdocs-quiz" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocs_quiz-{{ version }}.tar.gz
  sha256: 146abc76e4f21818ac167b6afb6e845cf548fe50af710ca6d9127a3c3cf33307

build:
  noarch: python
  entry_points:
    - mkdocs-quiz = mkdocs_quiz.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.0.0
    - importlib-resources >=5.0

test:
  imports:
    - mkdocs_quiz
  commands:
    - mkdocs-quiz --help
  requires:
    - python {{ python_min }}

about:
  home: https://ewels.github.io/mkdocs-quiz/
  doc_url: https://ewels.github.io/mkdocs-quiz/
  dev_url: https://github.com/ewels/mkdocs-quiz
  summary: A MkDocs plugin to create interactive quizzes in your markdown.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ewels
    - skyface753
